"""Simulation engine — backtesting, paper trading, and performance metrics."""

from traderbot.simulation.adaptation import (
    AdaptationConfig,
    AdaptationResult,
    MarketCategory,
    Posterior,
    Prior,
    StrategyAdjustment,
)
from traderbot.simulation.data_loader import DataLoader, DataQualityReport, QualityFlag
from traderbot.simulation.engine import (
    BacktestEngine,
    BacktestResult,
    BacktestTrade,
    Context,
    Signal,
    SlippageModel,
    Strategy,
)
from traderbot.simulation.paper_trader import (
    PaperFill,
    PaperPortfolio,
    PaperPosition,
    PaperSlippageModel,
    PaperTrader,
)
from traderbot.simulation.performance import (
    MultiStrategyComparison,
    StrategyComparison,
    compare_strategies,
    compare_strategies_multi,
    compute_brier_score,
    compute_calmar,
    compute_edge_capture,
    compute_fill_rate,
    compute_max_drawdown,
    compute_metrics,
    compute_sharpe,
    compute_win_rate,
)
from traderbot.simulation.profiles import (
    AGGRESSIVE,
    CONSERVATIVE,
    MODERATE,
    PRESETS,
    StrategyProfile,
    compare_profiles,
    compare_strategies_extended,
    run_profiles,
)

__all__ = [
    "AGGRESSIVE",
    "CONSERVATIVE",
    "MODERATE",
    "PRESETS",
    "AdaptationConfig",
    "AdaptationResult",
    "BacktestEngine",
    "BacktestResult",
    "BacktestTrade",
    "Context",
    "DataLoader",
    "DataQualityReport",
    "MarketCategory",
    "MultiStrategyComparison",
    "PaperFill",
    "PaperPortfolio",
    "PaperPosition",
    "PaperSlippageModel",
    "PaperTrader",
    "Posterior",
    "Prior",
    "QualityFlag",
    "Signal",
    "SlippageModel",
    "Strategy",
    "StrategyAdjustment",
    "StrategyComparison",
    "StrategyProfile",
    "compare_profiles",
    "compare_strategies",
    "compare_strategies_extended",
    "compare_strategies_multi",
    "compute_brier_score",
    "compute_calmar",
    "compute_edge_capture",
    "compute_fill_rate",
    "compute_max_drawdown",
    "compute_metrics",
    "compute_sharpe",
    "compute_win_rate",
    "run_profiles",
]
