"""Tests for traderbot.kalshi.pinning — TLS SPKI certificate pinning."""

from __future__ import annotations

import base64
from unittest.mock import MagicMock, patch

import pytest

from traderbot.kalshi.pinning import (
    CertPinningError,
    PinnedSSLContext,
    compute_spki_pin,
    verify_spki_pin,
)

# Test fixtures generated from ephemeral RSA keys for deterministic SPKI pin tests.
# Generated by: python -c "from cryptography.hazmat.primitives.asymmetric import rsa; "
TEST_CERT_DER = base64.b64decode(
    "MIICrTCCAZWgAwIBAgIBATANBgkqhkiG9w0BAQsFADAaMRgwFgYDVQQDDA90ZXN0LmthbHNoaS5jb20w"
    "HhcNMjYwNTIyMjM1MzQyWhcNMjcwNTIyMjM1MzQyWjAaMRgwFgYDVQQDDA90ZXN0LmthbHNoaS5jb20w"
    "ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCwAeD2+DGCZyZ3h8BxMdH7Z4nahjZjq9IwWO2g"
    "l0ORhX8kB9TdlBwUQUk40aAC+YhumUCbgUGPAUOOAmmfiiZqM83t0jxpLrmeaYjBYWvUCsq655dkFI5h"
    "gntoUNEQKsAHiHKk2sjoOEkJuwp/vz6KPVJotWMiwPYlpMbtEqZeXheMp3TPPXRv3rE5F7hrHPOIc5ut"
    "Et4VBeZgaCUngqUVyxOq0x8IeDbGSit793Zl0USGiFLy9PtBWOm99JSV7PwE+8QI4NGJQNA0J6ExloP+"
    "XnaKBknUbqjiIn4v54pWw6lUTW11iklha1ddt5al1Vvs/yOsQGONK6+Exy6NA4L3AgMBAAEwDQYJKoZI"
    "hvcNAQELBQADggEBABxjylRoy83FhvzLyvBulfrQgkkTxM+AUwBTZrSqRdBSIrxVTP2g2KWGaaherA/p"
    "gAViK+OsnssFpdEoIuiZwjLqBa/awAFexLzJ+JLOO5F0TJZXuSzvFIkBeGOlnRcwWpIlsm/JuGZkYyAv"
    "IHrz6axQpUWETn9panBNXyHFdwQrt0oa4cHFxn0+/nWE/QNRd8XmuhAIltY2P1URMyWOsderby64DoSHz"
    "fQdvr6/5XKvAznYl+KTS0jbMXsZIxIS6AOhfdaDtd7LRKu0tvI+fNAO0PonZsiqkeFun+mc//8RYmQyJ"
    "f56MnvO7aXJOa5WFW0i854Tjk+RbL4sUBajLoY="
)
TEST_SPKI_PIN = "CZCa681iMML2EQ5AcNfJispjbLUPoFXQ8DXUQd/VPRI="
WRONG_SPKI_PIN = "6oM0VK60Qvmg6RKc5QRwC0c9tbjM15ZqA8D40DCSGmc="


class TestComputeSpkiPin:
    def test_returns_expected_pin_for_known_cert(self) -> None:
        result = compute_spki_pin(TEST_CERT_DER)
        assert result == TEST_SPKI_PIN

    def test_pin_is_stable_across_calls(self) -> None:
        p1 = compute_spki_pin(TEST_CERT_DER)
        p2 = compute_spki_pin(TEST_CERT_DER)
        assert p1 == p2 == TEST_SPKI_PIN

    def test_pin_is_base64_string(self) -> None:
        result = compute_spki_pin(TEST_CERT_DER)
        base64.b64decode(result)
        assert isinstance(result, str)


class TestVerifySpkiPin:
    def test_matching_pin_returns_pin(self) -> None:
        result = verify_spki_pin(TEST_CERT_DER, frozenset({TEST_SPKI_PIN}))
        assert result == TEST_SPKI_PIN

    def test_returns_pin_when_multiple_trusted(self) -> None:
        result = verify_spki_pin(
            TEST_CERT_DER, frozenset({WRONG_SPKI_PIN, TEST_SPKI_PIN})
        )
        assert result == TEST_SPKI_PIN

    def test_non_matching_pin_raises(self) -> None:
        with pytest.raises(CertPinningError, match="SPKI pin mismatch"):
            verify_spki_pin(TEST_CERT_DER, frozenset({WRONG_SPKI_PIN}))

    def test_empty_trusted_set_raises(self) -> None:
        with pytest.raises(CertPinningError, match="SPKI pin mismatch"):
            verify_spki_pin(TEST_CERT_DER, frozenset())

    def test_empty_cert_raises(self) -> None:
        with pytest.raises(ValueError):
            compute_spki_pin(b"")
